---
# Base setup
- hosts: all
  roles: 
    - role: wcl-common

# Perform the Setup of the components
- include: setup-db.yml
- include: setup-app.yml

# Do the code / app deployment
- include: deploy-app.yml
